=== Fashionablylatte/chessio/config/engine-config.dtd
<!-- This is a schema for an engine configuration file. -->
<!ELEMENT engine (location, options)>

<!-- This is the location of the exe file -->
<!ELEMENT location (#PCDATA)>

<!-- This is the set of options for the engine. -->
<!ELEMENT options (options?)>

<!-- This is an individual option for the engine. -->
<!ELEMENT option (name, value)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT value (#PCDATA)>

=== Fashionablylatte/chessio/config/stockfish-config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Config file for the engine in use. -->
<!DOCTYPE engine-config SYSTEM "config/engine-config.dtd">
<engine>
    <location>engines/stockfish_20011801_x64.exe</location>
    <options>
        <option>
            <name>Threads</name>
            <value>2</value>
        </option>
        <option>
            <name>Slow Mover</name>
            <value>20</value>
        </option>
    </options>
</engine>
